ALTER TABLE buy RENAME COLUMN reciever TO receiver;
-- @BLOCK
ALTER TABLE buy MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;
-- @BLOCK
ALTER TABLE sell MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;
-- @BLOCK
INSERT INTO buy VALUES(1,'hatim',10,69);
INSERT INTO buy VALUES(2,'kaif',15,80);

-- @BLOCK
INSERT INTO sell VALUES(1,'kaif',10,69);
INSERT INTO sell VALUES(2,'hatim',15,80);